version: '3.9'
services:      
    web:
        build: .
        working_dir: /code/app
        command: uvicorn main:app --host 0.0.0.0 --reload
        environment:
          DEBUG: 1
        volumes:
          - ./app:/code/app
        ports:
        - "8009:8000"
        networks:
        - demo
    # redis:  
    #   image: redis:latest
    #   user: root
    #   restart: always
    #   ports:
    #     - 6379:6379
    #   volumes:
    #     - ./conf:/opt/local/bitnami/redis/etc
    #   environment:
    #     - ALLOW_EMPTY_PASSWORD=yes
    #   networks:
    #     - redis

# networks:
#   redis:
#     external:
#       name: redis
networks:
  demo:
    name: demo
    driver: bridge